### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by SHuang-Broad** [jwalabroad/SnowTools#1]
Hi Jeremiah,

I was compiling SnowTools on my machine and was hit by the following error:

    MiniRules.cpp:535:8: error: use of undeclared identifier 'atm'
    MiniRules.cpp:540:12: error: expected unqualified-id
    
I checked and found that possibly the cause is lack of #ifndef __APPLE__ #endif pair around the lines.

Steve

**Comment by jwalabroad** [comment]
Hi Steve, I haven't tested compiling on a Mac for a while. The Aho-Corasick library doesn't compile on osx, which is why I have the pre-processor ifelse. This should work on the Broad Unix system though, just make sure to configure with the --with-boost option with a path to installed boost libraries. I'm trying again on osx though and will let you know.

**Comment by jwalabroad** [comment]
Just made your suggested change and tested it on Mac, and it works great. I updated the README with better installation instructions too.

**Comment by SHuang-Broad** [comment]
Great! Thanks for the pointer to boost.
